# Generated by Django 5.2.11 on 2026-03-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100, unique=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_path', models.CharField(max_length=500)),
                ('n_laptops', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('text_search', 'Text Search'), ('similar', 'Similar Items'), ('preferences', 'Preferences'), ('personalized', 'Personalized')], max_length=50)),
                ('query_data', models.JSONField()),
                ('results_count', models.IntegerField(default=0)),
                ('response_time_ms', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['query_type'], name='api_recomme_query_t_10eceb_idx'), models.Index(fields=['timestamp'], name='api_recomme_timesta_d9d975_idx'), models.Index(fields=['model_version'], name='api_recomme_model_v_1cbc89_idx')],
            },
        ),
    ]
